

<h1 style="color:#C2185B; font-size:42px; font-weight:bold;">
🏠 House Price Prediction
</h1>




**AIM:**  
Predict house prices using machine learning techniques on a real dataset, and understand which features influence price the most.


## 1. Import Required Libraries

We import libraries for data handling, visualization, and machine learning.


In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error


## 2. Load Dataset

Load the CSV file containing house features and sale prices.


In [3]:
df = pd.read_csv(r"C:\Users\a\OneDrive\Desktop\House_price_prediction\data.csv")

df.head()


Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

## 3. Data Overview

Check the shape, data types, and basic statistical summary to understand the dataset.


In [4]:
df.shape

(1460, 81)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   Alley          91 non-null     object 
 7   LotShape       1460 non-null   object 
 8   LandContour    1460 non-null   object 
 9   Utilities      1460 non-null   object 
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [6]:
df.describe()

Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000   
mean    730.500000    56.897260    70.049958   10516.828082     6.099315   
std     421.610009    42.300571    24.284752    9981.264932     1.382997   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     365.750000    20.000000    59.000000    7553.500000     5.000000   
50%     730.500000    50.000000    69.000000    9478.500000     6.000000   
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000   
max    1460.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000  ...   
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726  ...   
std       1.112799    30.202904     20.645407   181.066207   456.098091  ...   
min       1.000000  1872.000000   1950.000000     0.000000     0.000000  ...   
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000  ...   
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000  ...   
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000  ...   
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000  ...   

        WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  ScreenPorch  \
count  1460.000000  1460.000000    1460.000000  1460.000000  1460.000000   
mean     94.244521    46.660274      21.954110     3.409589    15.060959   
std     125.338794    66.256028      61.119149    29.317331    55.757415   
min       0.000000     0.000000       0.000000     0.000000     0.000000   
25%       0.000000     0.000000       0.000000     0.000000     0.000000   
50%       0.000000    25.000000       0.000000     0.000000     0.000000   
75%     168.000000    68.000000       0.000000     0.000000     0.000000   
max     857.000000   547.000000     552.000000   508.000000   480.000000   

          PoolArea       MiscVal       MoSold       YrSold      SalePrice  
count  1460.000000   1460.000000  1460.000000  1460.000000    1460.000000  
mean      2.758904     43.489041     6.321918  2007.815753  180921.195890  
std      40.177307    496.123024     2.703626     1.328095   79442.502883  
min       0.000000      0.000000     1.000000  2006.000000   34900.000000  
25%       0.000000      0.000000     5.000000  2007.000000  129975.000000  
50%       0.000000      0.000000     6.000000  2008.000000  163000.000000  
75%       0.000000      0.000000     8.000000  2009.000000  214000.000000  
max     738.000000  15500.000000    12.000000  2010.000000  755000.000000  

[8 rows x 38 columns]

## 4. Missing Values Check

Check which columns have missing values and how many.


In [7]:
df.isnull().sum().sort_values(ascending=False)


PoolQC         1453
MiscFeature    1406
Alley          1369
Fence          1179
MasVnrType      872
               ... 
ExterQual         0
Exterior2nd       0
Exterior1st       0
RoofMatl          0
SalePrice         0
Length: 81, dtype: int64

## 5. Handle Missing Values

- Numerical columns → median  
- Categorical columns → mode


In [8]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns


In [9]:
for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)


C:\Users\a\AppData\Local\Temp\ipykernel_15808\3421764164.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)


In [10]:
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)


C:\Users\a\AppData\Local\Temp\ipykernel_15808\3902818140.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)


In [11]:
df.isnull().sum().sum()


0

## 6. Encode Categorical Variables

Convert categorical columns to numeric using one-hot encoding.


In [15]:
df_encoded = pd.get_dummies(df, drop_first=True)


In [16]:
df_encoded.shape


(1460, 246)

## 7. Define Features and Target

X → all features except 'SalePrice'  
y → target column 'SalePrice'


In [17]:
X = df_encoded.drop('SalePrice', axis=1)
y = df_encoded['SalePrice']


## 8. Split Data into Training and Testing Sets

80% training, 20% testing to evaluate model performance on unseen data.


In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [19]:
X_train.shape, X_test.shape


((1168, 245), (292, 245))

## 9. Train Linear Regression Model

This is our baseline model to compare with advanced models.


In [20]:
from sklearn.linear_model import LinearRegression

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)


LinearRegression()

## 10. Evaluate Linear Regression

Predict house prices and calculate R² score and RMSE.


In [21]:
y_pred = lr_model.predict(X_test)


In [22]:
r2 = r2_score(y_test, y_pred)
r2


0.6554926552252502

In [23]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
rmse


51405.09425333459

## 11. Train Random Forest Regressor

Random Forest handles non-linear patterns better and improves prediction accuracy.


In [24]:
from sklearn.ensemble import RandomForestRegressor


In [26]:
rf_model = RandomForestRegressor(
    n_estimators=100,      # 100 trees (balanced & safe)
    max_depth=20,         
    min_samples_split=10, 
    min_samples_leaf=5,  
    random_state=42,
    n_jobs=-1             
)


In [27]:
rf_model.fit(X_train, y_train)


RandomForestRegressor(max_depth=20, min_samples_leaf=5, min_samples_split=10,
                      n_jobs=-1, random_state=42)

## 12. Evaluate Random Forest

Predict house prices and calculate R² score and RMSE.


In [28]:
y_pred_rf = rf_model.predict(X_test)


In [29]:
rf_r2 = r2_score(y_test, y_pred_rf)
rf_rmse = np.sqrt(mean_squared_error(y_test, y_pred_rf))

rf_r2, rf_rmse


(0.8697044066190798, 31613.44183398369)

## 13. Feature Importance

Identify top features that influence house prices the most.


In [30]:
feature_importance = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': rf_model.feature_importances_
}).sort_values(by='Importance', ascending=False)

feature_importance.head(10)


Feature  Importance
4   OverallQual    0.598617
16    GrLivArea    0.130636
12  TotalBsmtSF    0.036703
9    BsmtFinSF1    0.032981
13     1stFlrSF    0.024674
27   GarageArea    0.016359
3       LotArea    0.015127
26   GarageCars    0.013933
6     YearBuilt    0.010891
14     2ndFlrSF    0.009699

## 14. Sample House Price Prediction

Predict price for a single house from the test set.


In [31]:
sample_house = X_test.iloc[0]


In [32]:
predicted_price = rf_model.predict([sample_house])
predicted_price


C:\Users\a\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([140756.95226496])

In [33]:
actual_price = y_test.iloc[0]

actual_price


154500

In [34]:
print("Actual House Price   :", actual_price)
print("Predicted House Price:", predicted_price[0])


Actual House Price   : 154500
Predicted House Price: 140756.9522649586


## 15. Model Comparison

We compare the performance of Linear Regression and Random Forest Regressor models to select the best model for house price prediction.


In [37]:
# Linear Regression Prediction
y_pred_lr = lr_model.predict(X_test)

# Metrics
r2_lr = r2_score(y_test, y_pred_lr)
rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))

print("Linear Regression R2:", r2_lr)
print("Linear Regression RMSE:", rmse_lr)


Linear Regression R2: 0.6554926552252502
Linear Regression RMSE: 51405.09425333459


In [38]:
y_pred_rf = rf_model.predict(X_test)

r2_rf = r2_score(y_test, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))

print("Random Forest R2:", r2_rf)
print("Random Forest RMSE:", rmse_rf)


Random Forest R2: 0.8697044066190798
Random Forest RMSE: 31613.44183398369


In [39]:
comparison_df = pd.DataFrame({
    'Model': ['Linear Regression', 'Random Forest'],
    'R2 Score': [r2_lr, r2_rf],
    'RMSE': [rmse_lr, rmse_rf]
})

comparison_df


Model  R2 Score          RMSE
0  Linear Regression  0.655493  51405.094253
1      Random Forest  0.869704  31613.441834

## 16. Conclusion

- Random Forest Regressor performed the best with R² ≈ 0.87 and RMSE ≈ 31,613.
- Linear Regression was a decent baseline (R² ≈ 0.65, RMSE ≈ 51,405).
- Top features influencing house price:
    - OverallQual (construction quality)
    - GrLivArea (living area)
    - TotalBsmtSF (basement area)
    - Others: GarageArea, 1stFlrSF, LotArea
- This project demonstrates the effectiveness of Random Forest for real-world regression problems.
- The model can help predict house prices accurately and provide insights for buyers, sellers, and real estate planning.
